package paylm

// Model name constants for external access
const (
	// OpenAI Models
	GPT5                     = "gpt-5"
	GPT5Mini                 = "gpt-5-mini"
	GPT5Nano                 = "gpt-5-nano"
	GPT5ChatLatest           = "gpt-5-chat-latest"
	GPT5Codex                = "gpt-5-codex"
	GPT5Pro                  = "gpt-5-pro"
	GPT5SearchAPI            = "gpt-5-search-api"
	GPT41                    = "gpt-4.1"
	GPT41Mini                = "gpt-4.1-mini"
	GPT41Nano                = "gpt-4.1-nano"
	GPT4O                    = "gpt-4o"
	GPT4O20240513            = "gpt-4o-2024-05-13"
	GPT4OMini                = "gpt-4o-mini"
	GPTRealtime              = "gpt-realtime"
	GPTRealtimeMini          = "gpt-realtime-mini"
	GPT4ORealtimePreview     = "gpt-4o-realtime-preview"
	GPT4OMiniRealtimePreview = "gpt-4o-mini-realtime-preview"
	GPTAudio                 = "gpt-audio"
	GPTAudioMini             = "gpt-audio-mini"
	GPT4OAudioPreview        = "gpt-4o-audio-preview"
	GPT4OMiniAudioPreview    = "gpt-4o-mini-audio-preview"
	O1                       = "o1"
	O1Pro                    = "o1-pro"
	O3Pro                    = "o3-pro"
	O3                       = "o3"
	O3DeepResearch           = "o3-deep-research"
	O4Mini                   = "o4-mini"
	O4MiniDeepResearch       = "o4-mini-deep-research"
	O3Mini                   = "o3-mini"
	O1Mini                   = "o1-mini"
	CodexMiniLatest          = "codex-mini-latest"
	GPT4OMiniSearchPreview   = "gpt-4o-mini-search-preview"
	GPT4OSearchPreview       = "gpt-4o-search-preview"
	ComputerUsePreview       = "computer-use-preview"
	ChatGPT4OLatest          = "chatgpt-4o-latest"
	GPT4Turbo20240409        = "gpt-4-turbo-2024-04-09"
	GPT40125Preview          = "gpt-4-0125-preview"
	GPT41106Preview          = "gpt-4-1106-preview"
	GPT41106VisionPreview    = "gpt-4-1106-vision-preview"
	GPT40613                 = "gpt-4-0613"
	GPT40314                 = "gpt-4-0314"
	GPT432K                  = "gpt-4-32k"
	GPT35Turbo               = "gpt-3.5-turbo"
	GPT35Turbo0125           = "gpt-3.5-turbo-0125"
	GPT35Turbo1106           = "gpt-3.5-turbo-1106"
	GPT35Turbo0613           = "gpt-3.5-turbo-0613"
	GPT350301                = "gpt-3.5-0301"
	GPT35TurboInstruct       = "gpt-3.5-turbo-instruct"
	GPT35Turbo16K0613        = "gpt-3.5-turbo-16k-0613"
	Davinci002               = "davinci-002"
	Babbage002               = "babbage-002"

	// Anthropic Models
	Sonnet45 = "Sonnet 4.5"
	Haiku45  = "Haiku 4.5"
	Opus41   = "Opus 4.1"
	Sonnet4  = "Sonnet 4"
	Opus4    = "Opus 4"
	Sonnet37 = "Sonnet 3.7"
	Haiku35  = "Haiku 3.5"
	Opus3    = "Opus 3"
	Haiku3   = "Haiku 3"

	// Google DeepMind Models
	Gemini25Pro                = "Gemini 2.5 Pro"
	Gemini25Flash              = "Gemini 2.5 Flash"
	Gemini25FlashPreview       = "Gemini 2.5 Flash Preview"
	Gemini25FlashLite          = "Gemini 2.5 Flash-Lite"
	Gemini25FlashLitePreview   = "Gemini 2.5 Flash-Lite Preview"
	Gemini25FlashNativeAudio   = "Gemini 2.5 Flash Native Audio"
	Gemini25FlashImage         = "Gemini 2.5 Flash Image"
	Gemini25FlashPreviewTTS    = "Gemini 2.5 Flash Preview TTS"
	Gemini25ProPreviewTTS      = "Gemini 2.5 Pro Preview TTS"
	Gemini25ComputerUsePreview = "Gemini 2.5 Computer Use Preview"

	// Meta Models
	Llama4Maverick             = "Llama 4 Maverick"
	Llama4Scout                = "Llama 4 Scout"
	Llama3370BInstructTurbo    = "Llama 3.3 70B Instruct-Turbo"
	Llama323BInstructTurbo     = "Llama 3.2 3B Instruct Turbo"
	Llama31405BInstructTurbo   = "Llama 3.1 405B Instruct Turbo"
	Llama3170BInstructTurbo    = "Llama 3.1 70B Instruct Turbo"
	Llama318BInstructTurbo     = "Llama 3.1 8B Instruct Turbo"
	Llama370BInstructTurbo     = "Llama 3 70B Instruct Turbo"
	Llama370BInstructReference = "Llama 3 70B Instruct Reference"
	Llama38BInstructLite       = "Llama 3 8B Instruct Lite"
	LLaMA2                     = "LLaMA-2"
	LlamaGuard412B             = "Llama Guard 4 12B"
	LlamaGuard311BVisionTurbo  = "Llama Guard 3 11B Vision Turbo"
	LlamaGuard38B              = "Llama Guard 3 8B"
	LlamaGuard28B              = "Llama Guard 2 8B"
	SalesforceLlamaRankV18B    = "Salesforce Llama Rank V1 (8B)"

	// AWS Models
	AmazonNovaMicro = "Amazon Nova Micro"
	AmazonNovaLite  = "Amazon Nova Lite"
	AmazonNovaPro   = "Amazon Nova Pro"

	// Mistral AI Models
	Mistral7BInstruct = "Mistral 7B Instruct"
	MistralLarge      = "Mistral Large"
	MistralSmall      = "Mistral Small"
	MistralMedium     = "Mistral Medium"

	// Cohere Models
	CommandR7B      = "Command R7B"
	CommandR        = "Command R"
	CommandRPlus    = "Command R+"
	CommandA        = "Command A"
	AyaExpanse8B32B = "Aya Expanse (8B/32B)"

	// DeepSeek Models
	DeepSeekChat       = "DeepSeek Chat"
	DeepSeekReasoner   = "DeepSeek Reasoner"
	DeepSeekR1Global   = "DeepSeek R1 Global"
	DeepSeekR1DataZone = "DeepSeek R1 DataZone"
	DeepSeekV32Exp     = "DeepSeek V3.2-Exp"
)

// Service provider constants for external access
const (
	// AI Service Providers
	OpenAI         = "OpenAI"
	Anthropic      = "Anthropic"
	GoogleDeepMind = "Google DeepMind"
	Meta           = "Meta"
	AWS            = "AWS"
	MistralAI      = "Mistral AI"
	Cohere         = "Cohere"
	DeepSeek       = "DeepSeek"
	Custom         = "Custom"
)
